# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fne2ghDSxNIpR3xGLHzPnCiPTJqGbSXB
"""

import pandas as pd

# Step 1: Import libraries
import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBRegressor
from sklearn.metrics import mean_squared_error, r2_score
import joblib


# Optional: Save the model
joblib.dump(xgb_model, "xgb_crop_yield_model.pkl")