# -*- coding: utf-8 -*-
"""app

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Z-C7R80RG_iF2gsHiYmY5BD7LM3y6MG1
"""

import streamlit as st
import numpy as np
import joblib

model = joblib.load("/content/xgb_crop_yield_model.pkl")
st.set_page_config(page_title="Crop Yield Predictor", layout="centered")
st.title("🌾 Crop Yield Prediction with XGBoost")

st.markdown("Enter the input values for each parameter:")

# Input fields
crop_year = st.number_input("Crop Year", min_value=1980, max_value=2020, value=2000)
area = st.number_input("Area (in hectares)", min_value=0.0, max_value=100000.0, value=1000.0)
rainfall = st.number_input("Annual Rainfall (mm)", min_value=0.0, max_value=5000.0, value=1000.0)
fertilizer = st.number_input("Fertilizer Used (kg)", min_value=0.0, max_value=1e7, value=10000.0)
pesticide = st.number_input("Pesticide Used (kg)", min_value=0.0, max_value=1e6, value=1000.0)

# Encoded inputs
crop_encoded = st.slider("Crop Encoded", 0, 50, 10)
season_encoded = st.slider("Season Encoded", 0, 10, 2)
state_encoded = st.slider("State Encoded", 0, 50, 5)

if st.button("Predict Yield"):
    input_features = np.array([
        crop_year, area, rainfall, fertilizer, pesticide,
        crop_encoded, season_encoded, state_encoded
    ]).reshape(1, -1)

    prediction = model.predict(input_features)[0]
    st.success(f"🌱 Predicted Crop Yield: {prediction:.2f} kg/ha")